#!/usr/bin/env node

var exec = require('child_process').exec
var port = process.argv[2] || 8888
var fs = require('fs')

var deleteFolderRecursive = function(path) {
    var files = [];
    if( fs.existsSync(path) ) {
        files = fs.readdirSync(path);
        files.forEach(function(file,index){
            var curPath = path + "/" + file;
            if(fs.statSync(curPath).isDirectory()) { // recurse
                deleteFolderRecursive(curPath);
            } else { // delete file
                fs.unlinkSync(curPath);
            }
        });
        fs.rmdirSync(path);
    }
};

try{
  deleteFolderRecursive('./log')
  fs.mkdirSync('log')
} catch(e){}

exec('ngrok -log=log/ngrok.log ' + port + '&> /dev/null')
setTimeout(function(){
  var log = fs.readFileSync('./log/ngrok.log','utf8')
  try {
    process.env['CLIENT_ADDRESS'] = log.match(/Tunnel established at +(.+)$/im)[1];
    require('./index.js')
  } catch(e){
    console.error("FAILED TO SET UP SERVER.")
  }
},5000);